# Generated by Django 5.1.1 on 2024-10-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_distribuidora', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('numero_cliente', models.CharField(max_length=50)),
                ('fecha_lectura_desde', models.DateField()),
                ('fecha_lectura_hasta', models.DateField()),
                ('consumo_total_kwh', models.FloatField()),
            ],
        ),
    ]
